services:
  web:
    image: wodby/apache:latest
    volumes:
      - ./web:/var/www/html
      - ./.devops/apache2/conf:/usr/local/apache2/conf/custom
    environment:
      - APACHE_INCLUDE_CONF=conf/custom/*.conf
    ports:
      - 80:80
      - 443:443
