---
services:
  web:
    image: wodby/apache:latest
    # If we need to customise our apache configuration, we can do by adding
    # .conf files in `./.devops/apache2/conf`.
    volumes:
      - ./web:/var/www/html
      - ./.devops/apache2/conf:/usr/local/apache2/conf/custom
    environment:
      - APACHE_INCLUDE_CONF=conf/custom/*.conf
      - APACHE_VHOST_PRESET=php
    ports:
      - 80:80
      - 443:443
  php:
    image: wodby/php:latest
    volumes:
      - ./web:/var/www/html
