---
services:
  web:
    image: wodby/apache:latest
    # If we need to customise our apache configuration, we can do by adding
    # .conf files in `./.devops/apache2/conf`.
    volumes:
      - ./web:/var/www/html
      - ./.devops/web/conf/custom-httpd-ssl.conf:/usr/local/apache2/conf/conf.d/custom-httpd-ssl.conf
      - /etc/ssl/certs/:/etc/ssl/certs
    environment:
      - APACHE_VHOST_PRESET=php
    ports:
      - 80:80
      - 443:443
  php:
    image: wodby/php:latest
    volumes:
      - ./web:/var/www/html
  db:
    image: wodby/mariadb:latest
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_PASSWORD=password
      - MYSQL_host=localhost
    volumes:
      - ~/.docker-volumes/devops-static/mysql:/var/lib/mysql
    ports:
      - 3306:3306
